id: ID7419777
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:05:19+00:00'
last_modified: '2022-06-08T05:02:24.246579+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01625
  title: གཞན་སྟོང་དབུ་མ་ཆེན་པོའི་ལྟ་ཁྲིད་རྡོ་རྗེ་ཟླ་བ་དྲི་མ་མེད་པའི་འོད་ཟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2533':
      image_group_id: I00KG02888
      title: ''
      total_pages: 34
      order: 1
      base_file: 2533.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
